import 'server-only'

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Where uploaded bytes actually live.
 *
 * Two backends behind one interface:
 *
 *   local disk  — development, and any host with a persistent volume.
 *   Vercel Blob — serverless hosts, whose filesystem is ephemeral. An Aadhaar
 *                 scan written to a Vercel function's disk survives a few
 *                 minutes and is then gone, which looks to the person who
 *                 uploaded it exactly like it worked.
 *
 * The backend is chosen by whether Blob credentials are present, so a
 * developer with no Vercel account keeps working against the disk and
 * nothing in the calling code changes. Callers (lib/storage.ts for applicant
 * documents, lib/media.ts for the media library) go through these four
 * functions and never touch a filesystem or an SDK directly — that is what
 * made this swap a contained change rather than a rewrite.
 *
 * THE STORE MUST BE PRIVATE.
 * --------------------------
 * Create it with `access: 'private'`. A public store hands out URLs that work
 * for anyone who has them, and this application stores identity documents.
 * Private blobs are readable only with the token, which is why both files are
 * still served through routes that check a session first — /api/uploads/[id]
 * and /media/[id]/[name]. Vercel fixes a store's access mode at creation and
 * it cannot be changed afterwards, so getting this wrong means making a new
 * store.
 */

export type Bucket = 'uploads' | 'media'

/**
 * `||` rather than `??`: an empty value means "not configured". `UPLOAD_DIR=`
 * with nothing after it is what you get from copying the example file, and
 * with `??` it resolved to "", which path.join treats as the working
 * directory — writing identity documents into the project root.
 */
const ROOTS: Record<Bucket, string> = {
  uploads: process.env.UPLOAD_DIR || path.join(process.cwd(), 'var', 'uploads'),
  media: process.env.MEDIA_DIR || path.join(process.cwd(), 'var', 'media'),
}

/**
 * OIDC (BLOB_STORE_ID) is how a project connected to a store authenticates on
 * Vercel; BLOB_READ_WRITE_TOKEN is the long-lived token used elsewhere. Either
 * means "use Blob".
 */
export function usingBlob(): boolean {
  return Boolean(process.env.BLOB_READ_WRITE_TOKEN || process.env.BLOB_STORE_ID)
}

/** Namespaced so the two buckets cannot collide inside one store. */
function blobPath(bucket: Bucket, key: string): string {
  return `${bucket}/${key}`
}

/** Local path for a key, refusing anything that escapes its root. */
function localPath(bucket: Bucket, key: string): string | null {
  const root = path.resolve(ROOTS[bucket])
  const target = path.resolve(root, key)
  // Keys are generated by this application, never supplied by a caller, but
  // confirming that costs nothing and closes off traversal for good.
  return target === root || target.startsWith(root + path.sep) ? target : null
}

export async function putObject(
  bucket: Bucket,
  key: string,
  bytes: Buffer,
  contentType: string
): Promise<void> {
  if (usingBlob()) {
    const { put } = await import('@vercel/blob')
    await put(blobPath(bucket, key), bytes, {
      access: 'private',
      contentType,
      // Keys already carry their own randomness, and the database records the
      // exact key. A suffix would make the stored key wrong.
      addRandomSuffix: false,
      // Re-encoding the same media id must not fail on an existing pathname.
      allowOverwrite: true,
    })
    return
  }

  const target = localPath(bucket, key)
  if (!target) throw new Error('Refusing to write outside the storage root.')
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, bytes)
}

export async function getObject(bucket: Bucket, key: string): Promise<Buffer | null> {
  if (usingBlob()) {
    const { get } = await import('@vercel/blob')
    try {
      const res = await get(blobPath(bucket, key), { access: 'private' })
      if (!res || res.statusCode !== 200 || !res.stream) return null
      const chunks: Uint8Array[] = []
      const reader = res.stream.getReader()
      try {
        for (;;) {
          const { done, value } = await reader.read()
          if (done) break
          if (value) chunks.push(value)
        }
      } finally {
        reader.releaseLock()
      }
      return Buffer.concat(chunks)
    } catch {
      // A missing blob is a miss, not a fault: the caller renders a 404.
      return null
    }
  }

  const target = localPath(bucket, key)
  if (!target) return null
  try {
    return await readFile(target)
  } catch {
    return null
  }
}

export async function deleteObject(bucket: Bucket, key: string): Promise<void> {
  if (usingBlob()) {
    const { del } = await import('@vercel/blob')
    await del(blobPath(bucket, key)).catch(() => {})
    return
  }
  const target = localPath(bucket, key)
  if (target) await rm(target, { force: true }).catch(() => {})
}

/**
 * Everything under a prefix — one media item's whole set of encoded variants.
 * Blob has no recursive delete, so the keys are listed and removed together.
 */
export async function deletePrefix(bucket: Bucket, prefix: string): Promise<void> {
  if (usingBlob()) {
    const { del, list } = await import('@vercel/blob')
    try {
      const full = blobPath(bucket, prefix.endsWith('/') ? prefix : `${prefix}/`)
      const { blobs } = await list({ prefix: full, limit: 1000 })
      if (blobs.length) await del(blobs.map((b) => b.url))
    } catch {
      // Leaving orphaned bytes is survivable; failing the delete is not.
    }
    return
  }
  const target = localPath(bucket, prefix)
  if (target) await rm(target, { recursive: true, force: true }).catch(() => {})
}
